### PR TITLE
Publish 2.4.0 recipe

### PR DESCRIPTION
**Pull request by lewismc**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lewismc** [comment]
@conda-forge-admin please rerender

**Comment by lewismc** [comment]
@conda-forge/core any ideas on what happened when I tried to re-render? Thank you

**Comment by ocefpaf** [comment]
> @conda-forge/core any ideas on what happened when I tried to re-render? Thank you

Sometimes the webservices may be down or something it not OK with the recipe. The only way to debug that is to try to re-render locally. See https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Comment by lewismc** [comment]
Addressed in https://github.com/conda-forge/podaacpy-feedstock/pull/22

Thank you @ocefpaf and @scopatz for checking in. Appreciated ! :)

**Pull request closed without merging**
