### PR TITLE
Update feedstock to podaacpy 1.6.0

### PR DESCRIPTION
**Pull request by lewismc**
Trivial update for Podaacpy 1.6.0 release.

### CODE REVIEW

**Comment by agoodm** [comment]
@lewismc Since the AppVeyor (Windows) and Travis CI (macOS) builds failed / didn't finish, only the linux versions of the package got uploaded to conda-forge, so another PR will need to be submitted.  We should not ever merge unless all tests are green.

**Comment by lewismc** [comment]
Bugger. OK doke will submit one more in a wee while. Thanks @agoodm

**Comment by agoodm** [comment]
Actually, I apologize for jumping the gun @lewismc. Although it is generally good to wait until all tests are green before merging, the CI builds should run again after each merge to master, and it is those builds that are uploaded to conda-forge. In this case the issue seems to not be on our end, so I guess we should wait about a day or so and see if macOS and Windows versions are still not uploaded.

**Comment by lewismc** [comment]
Cool. Ta

**Comment by agoodm** [comment]
Since the builds failed, I will make another PR and see if they pass. Otherwise I'll contact the conda-forge team.

**Pull request merged**
